@Tasks_Api_HostAddress = http://localhost:5244

GET {{Tasks_Api_HostAddress}}/weatherforecast/
Accept: application/json

###

GET {{Tasks_Api_HostAddress}}/tasks
Accept: application/json

###

GET {{Tasks_Api_HostAddress}}/tasks/1
Accept: application/json

###