@Tasks_Api_HostAddress = http://localhost:5244

GET {{Tasks_Api_HostAddress}}/weatherforecast/
Accept: application/json

###

GET {{Tasks_Api_HostAddress}}/tasks/
Accept: application/json

###

GET {{Tasks_Api_HostAddress}}/tasks/1
Accept: application/json

###

POST {{Tasks_Api_HostAddress}}/tasks/
Content-Type: application/json

{
    "name": "walk the dog"
}

###

POST {{Tasks_Api_HostAddress}}/tasks/
Content-Type: application/json

{
    "name": "grind leetcode",
    "isUrgent": true,
    "due": "2024-12-12T22:00:00"
}

###

PUT {{Tasks_Api_HostAddress}}/tasks/2
Content-Type: application/json

{   
    "name": "do the laundry",
    "isUrgent": true,
    "due": "2024-05-12T00:00:00"
}

###

DELETE {{Tasks_Api_HostAddress}}/tasks/4
Accept: application/json